#日志属性
log:
  level: "debug"

#服务端
server:
  port: 443 #端口
  num: 2 #服务端进程数

model:
  svm_path: models/clf.pkl
  ifashion_path: models/ifashion.pkl 

upload:
  max_size: 5 #MB
  save_path: static
  url: https://yige.foolai.top/static

weather:
  city_url: http://apis.map.qq.com/ws/geocoder/v1/
  city_key: OGRBZ-ZMQCG-EZ3QE-IMQI4-QKJ4S-XOB6U
  xz_api: https://api.seniverse.com/v3/weather/daily.json
  xz_key: SyjMKzti58YKqnnd1
  xz_uid: PPjfaiK81XoIYa2Ne

login:
  appid: wx7d40498f333efe4e
  appsecret: a5b27a6e61645049affc9fcd7071d837

mysql:
  host: '127.0.0.1'
  port: 3306
  user: root 
  password: '112119110'
  db: yige
